
=head1 NAME

virt-manager - display the virtual machine desktop management tool

=head1 SYNOPSIS

B<virt-manager> [OPTIONS]

=head1 DESCRIPTION

B<virt-manager> is a desktop tool for managing virtual machines. It
provides the ability to control the lifecycle of existing machines
(bootup/shutdown,pause/resume,suspend/restore), provision new virtual
machines and various types of store, manage virtual networks,
access the graphical console of virtual machines, and view performance
statistics, all done locally or remotely.

=head1 OPTIONS

The following options are accepted when running C<virt-manager>:

=over 4

=item -h, -help

Display command line help summary

=item -c URI, --connect=URI

Specify the hypervisor connection URI

=item --debug

List debugging output to the console (normally this is only logged in
~/.virt-manager/virt-manager.log). This function implies --no-fork.

=item --no-fork

Don't fork C<virt-manager> off into the backround: run it blocking the
current terminal. Useful for seeing possible errors dumped to stdout/stderr.

=item --no-dbus

Disable the DBus API used for remote control of the C<virt-manager> UI

=item --no-conn-autostart

Don't autostart any libvirt connections when launching C<virt-manager>.

=item --show-domain-creator

Display the wizard for creating new virtual machines

=item --show-domain-editor=UUID

Display the dialog for editing properties of the virtual machine with
unique ID matching C<UUID>

=item --show-domain-performance=UUID

Display the dialog for monitoring performance of the virtual machine with
unique ID matching C<UUID>

=item --show-domain-console=UUID

Display the virtual console of the virtual machine with
unique ID matching C<UUID>

=item --show-host-summary

Display the main window summarizing performance for all virtual machines
on the host.

=back

=head1 AUTHOR

Written by Daniel P. Berrange and Cole Robinson.

=head1 BUGS

Please see L<http://virt-manager.org/page/BugReporting>

=head1 COPYRIGHT

Copyright (C) 2006-2007 Red Hat, Inc, and various contributors.
This is free software. You may redistribute copies of it under the terms of the GNU General
Public License C<http://www.gnu.org/licenses/gpl.html>. There is NO WARRANTY, to the extent
permitted by law.

=head1 SEE ALSO

C<virsh(1)>, C<virt-viewer(1)>, the project website C<http://virt-manager.org>

=cut

