=pod

=head1 NAME

virt-xml - XXX

=head1 SYNOPSIS

B<virt-xml> XXX

=head1 DESCRIPTION

B<virt-xml> XXX

=head1 OPTIONS

=over 4

=item -h, --help

Show the help message and exit

=back

=head2 BAR SECTION

=over 2

=item  FOO

FOO

=item  BAR

BAR

=back

=head2 Miscellaneous Options

=over 2

=item -q, --quiet

Avoid verbose output.

=item -d, --debug

Print debugging information

=item --dry-run

Proceed through the conversion process, but don't convert disks or actually
write any converted files.

=back

=head1 EXAMPLES

XXX

=head1 BUGS

Please see http://virt-manager.org/page/BugReporting

=head1 COPYRIGHT

Copyright (C) Red Hat, Inc, and various contributors.
This is free software. You may redistribute copies of it under the terms
of the GNU General Public License C<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 SEE ALSO

L<virt-install(1)>, the project website C<http://virt-manager.org>

=cut
