# keytable_name_from_dom0:keymap_name_to_Xen
keytable = {
    "ar":"ar",
    "dk":"da",
    "de":"de",
    "de-ch":"de-ch",
    "gb":"en-gb",
    "us":"en-us",
    "es":"es",
    "":"et",
    "se_FI":"fi",
    "":"fo",
    "":"fr",
    "be":"fr-be",
    "":"fr-ca",
    "fr_CH":"fr_ch",
    "hr":"hr",
    "":"hu",
    "":"is",
    "it":"it",
    "jp106":"ja",
    "lt":"lt",
    "lv":"lv",
    "mk":"mk",
    "": "nl",
    "":"nl-be",
    "no":"no",
    "pl":"pl",
    "pt":"pt",
    "br":"pt-br",
    "br-abnt2":"pt-br",
    "ru":"ru",
    "sl":"sl",
    "":"sv",
    "th":"th",
    "tr":"tr",
    }

