#!/usr/bin/env python3
# Convenience wrapper for easily running virt-manager from the git tree

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

if "--qt" in sys.argv:
    sys.argv.remove("--qt")
    from qt.__main__ import main as qt_main
    sys.exit(qt_main())
else:
    from virtManager import virtmanager
    virtmanager.runcli()
