#!/usr/bin/python3
# Convenience wrapper for easily running virt-xml from the git tree

import os
import sys
sys.path.insert(0, os.path.dirname(__file__))

from virtinst import virtxml
virtxml.runcli()
